# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: composition.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='composition.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x11\x63omposition.proto\"3\n\x0b\x43omposition\x12\x11\n\tchampions\x18\x01 \x03(\x05\x12\x11\n\tsynergies\x18\x02 \x03(\x05\"5\n\x0f\x43ompositionList\x12\"\n\x0c\x63ompositions\x18\x01 \x03(\x0b\x32\x0c.Compositionb\x06proto3'
)




_COMPOSITION = _descriptor.Descriptor(
  name='Composition',
  full_name='Composition',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='champions', full_name='Composition.champions', index=0,
      number=1, type=5, cpp_type=1, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='synergies', full_name='Composition.synergies', index=1,
      number=2, type=5, cpp_type=1, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=21,
  serialized_end=72,
)


_COMPOSITIONLIST = _descriptor.Descriptor(
  name='CompositionList',
  full_name='CompositionList',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='compositions', full_name='CompositionList.compositions', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=74,
  serialized_end=127,
)

_COMPOSITIONLIST.fields_by_name['compositions'].message_type = _COMPOSITION
DESCRIPTOR.message_types_by_name['Composition'] = _COMPOSITION
DESCRIPTOR.message_types_by_name['CompositionList'] = _COMPOSITIONLIST
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Composition = _reflection.GeneratedProtocolMessageType('Composition', (_message.Message,), {
  'DESCRIPTOR' : _COMPOSITION,
  '__module__' : 'composition_pb2'
  # @@protoc_insertion_point(class_scope:Composition)
  })
_sym_db.RegisterMessage(Composition)

CompositionList = _reflection.GeneratedProtocolMessageType('CompositionList', (_message.Message,), {
  'DESCRIPTOR' : _COMPOSITIONLIST,
  '__module__' : 'composition_pb2'
  # @@protoc_insertion_point(class_scope:CompositionList)
  })
_sym_db.RegisterMessage(CompositionList)


# @@protoc_insertion_point(module_scope)
